version: 1.0.0.{build}

platform: x64

branches:
  only:
    - master

clone_folder: c:\gopath\src\github.com\jamsterwes\tiny-hacknplan

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - go get github.com/julienschmidt/httprouter

build_script:
  - go build -o tiny-hacknplan_%APPVEYOR_BUILD_VERSION%\server.exe -i .
  - xcopy public tiny-hacknplan_%APPVEYOR_BUILD_VERSION%\public /e /i

artifacts:
  - path: tiny-hacknplan_%APPVEYOR_BUILD_VERSION%